---
# tasks file for nginx

- include_vars: "{{ ansible_os_family }}.yml"

- include: "{{ ansible_os_family }}.yml"

- name: set uwsgi_params
  copy: src=files/uwsgi_params dest={{ nginx_uwsgi_params_path }}
  become: yes
  when: nginx_upstream_pass == 'uwsgi_pass'

- name: create ssl file paths
  file: path={{ item }} state=directory owner=root group=root mode=0700
  become: yes
  with_items:
    - "{{ nginx_ssl_cert_path | dirname }}"
    - "{{ nginx_ssl_key_path | dirname }}"
  when: nginx_ssl
  ignore_errors: true

- name: deploy ssl cert
  copy: src={{ nginx_ssl_cert }} dest={{ nginx_ssl_cert_path }}
  become: yes
  when: nginx_ssl_cert != ''

- name: deploy ssl key
  copy: src={{ nginx_ssl_key }} dest={{ nginx_ssl_key_path }}
  become: yes
  when: nginx_ssl_key != ''

- name: set nginx config
  template: src=templates/nginx.conf.j2
            dest={{ nginx_config_dir }}/{{ nginx_domain_name }}.conf
            mode=0600 owner=root group=root
  become: yes
  notify:
    - check nginx config
    - restart nginx
